name: Deploy N8N Backend via Render CLI

on:
  workflow_dispatch:
    inputs:
      workflow_n8n_path:
        description: 'N8N workflow to deploy'
        required: false
        default: 'docs/workflows/premiere-suites-demo-workflow.json'

concurrency:
  group: render-deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID: ${{ vars.RENDER_SERVICE_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Preflight (secrets, path)
        id: preflight
        shell: bash
        run: |
          set -euo pipefail

          # Fail fast if credentials/vars are missing
          : "${RENDER_API_KEY:?Missing RENDER_API_KEY secret}"
          : "${RENDER_SERVICE_ID:?Missing RENDER_SERVICE_ID variable}"

          # Resolve workflow path input (fallback to existing default)
          WORKFLOW_PATH="${{ github.event.inputs.workflow_n8n_path || 'docs/workflows/premiere-suites-demo-workflow.json' }}"
          WORKFLOW_PATH="${WORKFLOW_PATH%/}" # strip trailing slash, if any

          if [[ ! -f "$WORKFLOW_PATH" ]]; then
            echo "❌ Workflow file does not exist: $WORKFLOW_PATH" >&2
            exit 1
          fi

          # Export values for later steps
          echo "WORKFLOW_PATH=$WORKFLOW_PATH" >> "$GITHUB_ENV"
          echo "workflow_path=$WORKFLOW_PATH" >> "$GITHUB_OUTPUT"

          echo "✅ Preflight complete: workflow_path=$WORKFLOW_PATH"
