name: Deploy N8N Backend via Render CLI

on:
  workflow_dispatch:
    inputs:
      workflow_n8n_path:
        description: 'N8N workflow to deploy'
        required: false
        default: 'docs/workflows/premiere-suites-demo-workflow.json'

concurrency:
  group: render-deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID: ${{ vars.RENDER_SERVICE_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@

      - name: Preflight (secrets, variables)
        run: |
          if [ -z "${RENDER_API_KEY}" ]; then
            echo "RENDER_API_KEY is not set. Failing."
            exit 1
          fi
          if [ -z "${RENDER_SERVICE_ID}" ]; then
            echo "RENDER_SERVICE_ID is not set. Failing."
            exit 1
          fi
